spring:
  thymeleaf:
    cache: false
  datasource:
      url: jdbc:mysql://localhost:3306/community
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 201606
      type: com.alibaba.druid.pool.DruidDataSource
      maxActive: 20
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

logging:
  level:
    com.bin.dao: debug